#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:=$HOME/.config}"
export ZDOTDIR="${ZDOTDIR:=$XDG_CONFIG_HOME/zsh}"
source "$ZDOTDIR/.zshenv"

export CDPATH="$HOME/code/src/github.com/updater:$CDPATH"
eval "$(fasd --init auto)"

# path stuffs
export PATH=/Users/dillon.mcdowell/.local/bin:$PATH

# add functions
for file in $HOME/.config/zsh/functions/*(.); source $file

# add aliases
for file in $HOME/.config/zsh/aliases/*(.); source $file

# autoload -U compinit; compinit
FZF_COMPLETION_TRIGGER=''

source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
# eval "$(starship init zsh)"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
